CREATE TABLE "TSPA_STAGING" 
   (	
    "TRIPID" NUMBER, 
	"VENDOR_NAME" VARCHAR2(50), 
	"TRIP_DISTANCE" FLOAT, 
	"PICKUP_DATETIME" DATE, 
	"DROPOFF_DATETIME" DATE, 
	"PICKUP_LOCATION" VARCHAR2(100), 
	"DROPOFF_LOCATION" VARCHAR2(100), 
	"PASSENGER_COUNT" FLOAT, 
	"RATE_CODE" VARCHAR2(50), 
	"STORE_AND_FWD_FLAG" VARCHAR2(2), 
	"PAYMENT_TYPE" VARCHAR2(20), 
	"FARE_AMOUNT" FLOAT, 
	"MTA_TAX" FLOAT, 
	"IMPROVEMENT_SURCHARGE" FLOAT, 
	"TIP_AMOUNT" FLOAT, 
	"TOLLS_AMOUNT" FLOAT, 
	"TOTAL_AMOUNT" FLOAT, 
	"CONGESTION_SURCHARGE" , 
	"AIRPORT_FEE" FLOAT, 
	"CAR_TYPE" VARCHAR2(20)
   ) 