create table  transportation_service_analysis (
        tripid NUMBER,
        vendor_name varchar (50),
        trip_distance FLOAT,
        pickup_datetime DATE,
        dropoff_datetime DATE,
        pickup_location varchar(100),
        dropoff_location varchar(100),
        passenger_count FLOAT,
        rate_code FLOAT,
        store_and_fwd_flag VARCHAR(2),
        payment_type varchar(20),
        fare_amount FLOAT,
        mta_tax FLOAT,
        improvement_surcharge FLOAT,
        tip_amount FLOAT,
        tolls_amount FLOAT,
        total_amount FLOAT,
        congestion_surcharge FLOAT,
        airport_fee FLOAT,
        car_type varchar(20)       
)