create table  transportation_service_analysis (
        tripid NUMBER PRIMARY KEY,
        vendorid varchar (2),
        trip_distance FLOAT,
        pickup_datetime DATE,
        dropoff_datetime DATE,
        pulocationid NUMBER,
        dolocationid NUMBER,
        passenger_count FLOAT,
        ratecodeid FLOAT,
        store_and_fwd_flag VARCHAR(2),
        payment_type varchar(2),
        fare_amount FLOAT,
        mta_tax FLOAT,
        improvement_surcharge FLOAT,
        tip_amount FLOAT,
        tolls_amount FLOAT,
        total_amount FLOAT,
        congestion_surcharge FLOAT,
        airport_fee FLOAT,
        car_type number       
)